---
title: "My Goals While Enrolled in Cognitive Psychology"
description: |
  Take a look at some of my initial thoughts and goals while enrolled in a cognitive psychology course!
author:
  - name: Yuliya Cheban
    url: https://www.iopsych-baruch.com/yuliya-cheban
    affiliation: Baruch College
    affiliation_url: https://www.iopsych-baruch.com
date: 08-26-2020
bibliography: My Collection.bib
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```


# My Relatively Novice Perspective

Psychology has been at the forefront of my formal education for the better half of my life. As many in the field know, that could mean a slew of different things. On my end, that means I spend a majority of my day thinking about how to improve the world of organizations for applicants and employees. I recognize that for those not in this field, the connection between psychology and the world of work is not always abundantly clear. However, what binds most, if not all, psychologists together is the hope to understand the various mental processes (e.g., attention, perception, memory, creativity, etc..) our subjects of interest experience. I'm eager to be taking this course because increasing my expertise in an area that I view connects psychologists will make me a stronger and more confident learner.

That being said, my current understanding of Cognitive Psychology as a field is broad and relatively malleable as it can be interjected into conversations dealing with many other subject areas. I suppose this understanding of the field that I have necessitates I dig deeper into how cognitive psychology specifically lends itself to my field: Industrial-Organizational (I-O) Psychology; thus, I present some of my learning goals below.  

# Learning Goals

As I briefly sit and ruminate on some topic areas of I-O Psychology, I realize that all of the ones I think about frequently (particularly Employee Selection, Performance Management, and Training) are very deeply tied to Cognitive Psychology. I would like to use this section to do these areas justice by making explicit connections between them and Cognitive Psychology in my learning goals for the semester.

Over the course of this semester I hope to branch I-O Psychology and Cognitive Psychology by:

1. Understanding the impact memory has on how individuals get rated in selection and performance management practices.
2. Understanding how language, especially with multilingual individuals, impacts selection test scores; and especially, how we can use this information to build fair and valid assessments.
3. Understanding the concepts related to the decision making process of individuals who are incumbents in roles that require high risk taking behaviors.
4. Understanding how memory and learning (and the individual differences people exhibit between them) impact the effectiveness of employee training programs.

I have chosen these learning goals because they collectively integrate my favorite topics in my field. Below I present my topic of interest which is relatively independent from these because of its specificity. I'm interested to see how both my learning goals and my topic of interest develop or change as the semester progresses.

# Topic of Interest

My learning goals above are relatively broad, especially compared to my (current) focal interest in I-O Psychology which is applicant reactions to selection procedures. One of my core professional tenets is that I-O Psychologists have a responsibility to advocate for applicants and one way to do that is to commit to measuring how <b>and</b> why applicants react to, or perceive, processes a certain way. That being said, below I present a research question that may help me answer this using a cognitive approach.

## Overarching Research Question

- In what contexts (e.g., location or type of organization) do applicants perceive fairer selection processes and why?

I ask this question in a cognitive psychology course because I'm interested in furthering my understanding of how individuals perceive their environments, particularly in higher stakes contexts (e.g., job interviews).

# Closing Thought

I chose to use this specific blogging opportunity as a way to document my stream of consciousness about a topic I'm not completely confident in. As I proofread, I am increasingly more excited to be able to ground my work in cognitive psychology and immerse myself in its theories. 



